paths:
  asset_package:        etc/resources/aws/svg
  service_catalog_csv:  etc/resources/aws/service-catalog.csv
  assets_db:            xaligo-assets.db
  project_db:           .xaligo/project.db

item:
  icon_size: 32

serve:
  port: 8080
