// Explicit catalog -> AWS namespace mappings. These are not runtime guesses.
// CloudFormation models describe configuration, not every service operation.
export const namespaces = {
  'location-service':['Location'], 'well-architected-tool':['WellArchitected'], 'file-cache':['FSx'],
  'api-gateway': ['ApiGateway','ApiGatewayV2'], 'application-recovery-controller': ['Route53RecoveryControl','Route53RecoveryReadiness','ARCZonalShift','ARCRegionSwitch'],
  'client-vpn': ['EC2'], 'cloud-map': ['ServiceDiscovery'], 'cloud-wan': ['NetworkManager'], 'elastic-load-balancing': ['ElasticLoadBalancingV2','ElasticLoadBalancing'],
  'private-5g': [], 'privatelink': ['EC2'], 'site-to-site-vpn': ['EC2'], 'transit-gateway': ['EC2'], 'verified-access': ['EC2'], 'virtual-private-cloud': ['EC2'], 'vpc': ['EC2'],
  'ec2-auto-scaling': ['AutoScaling'], 'ec2-image-builder': ['ImageBuilder'], 'elastic-block-store': ['EC2','DLM'], 'elastic-container-registry': ['ECR','ECRPublic'],
  'elastic-container-service': ['ECS'], 'elastic-kubernetes-service': ['EKS'], 'eks-cloud': ['EKS'], 'ecs-anywhere': ['ECS'], 'fargate': ['ECS','EKS'],
  'elastic-vmware-service': ['EVS'], 'elastic-fabric-adapter': ['EC2'], 'nitro-enclaves': ['EC2'], 'lightsail-for-research': ['Lightsail'],
  'outposts-family': ['Outposts'], 'outposts-rack': ['Outposts'], 'outposts-servers': ['Outposts'], 'parallel-computing-service': ['PCS'],
  'serverless-application-repository': ['ServerlessRepo'], 'application-auto-scaling': ['ApplicationAutoScaling'], 'auto-scaling': ['AutoScalingPlans','AutoScaling'],
  'managed-grafana': ['Grafana'], 'managed-service-for-prometheus': ['APS'], 'systems-manager': ['SSM','SSMContacts','SSMIncidents'],
  'user-notifications': ['Notifications','NotificationsContacts'], 'resource-explorer': ['ResourceExplorer2'],
  'b2b-data-interchange': ['B2BI'], 'eventbridge': ['Events','Pipes','Scheduler','EventSchemas'], 'express-workflows': ['StepFunctions'],
  'managed-workflows-for-apache-airflow': ['MWAA'], 'mq': ['AmazonMQ'], 'step-functions': ['StepFunctions'],
  'application-migration-service': ['MGN'], 'database-migration-service': ['DMS'], 'elastic-disaster-recovery': ['DRS'], 'mainframe-modernization': ['M2'],
  'transfer-family': ['Transfer'], 'appstream-2': ['AppStream'], 'workspaces-family': ['WorkSpaces','WorkSpacesWeb','WorkSpacesThinClient'],
  'cloudhsm': ['CloudHSM'], 'iam-identity-center': ['SSO','IdentityStore'], 'identity-and-access-management': ['IAM','AccessAnalyzer','RolesAnywhere'],
  'key-management-service': ['KMS'], 'private-certificate-authority': ['ACMPCA'], 'resource-access-manager': ['RAM'],
  'macie': ['Macie2'], 'waf': ['WAFv2'], 'shield': ['Shield'], 'firewall-manager': ['FMS'],
  'data-firehose': ['KinesisFirehose'], 'glue-databrew': ['DataBrew'], 'kinesis-data-streams': ['Kinesis'], 'kinesis': ['Kinesis'],
  'managed-service-for-apache-flink': ['KinesisAnalyticsV2'], 'managed-streaming-for-apache-kafka': ['MSK','KafkaConnect'],
  'opensearch-service': ['OpenSearchService','OpenSearchServerless','OSIS'], 'sagemaker-ai': ['SageMaker'], 'sagemaker': ['SageMaker'],
  'sagemaker-ground-truth': ['SageMaker'], 'aurora': ['RDS'], 'documentdb': ['DocDB','DocDBElastic'], 'keyspaces': ['Cassandra'],
  'oracle-database-at-aws': ['ODB'], 'fsx-for-lustre': ['FSx'], 'fsx-for-netapp-ontap': ['FSx'], 'fsx-for-openzfs': ['FSx'], 'fsx-for-wfs': ['FSx'],
  's3-on-outposts': ['S3Outposts'], 's3-glacier': ['S3'], 'cost-and-usage-report': ['CUR','BCMDataExports'], 'cost-explorer': ['CE'],
  'reserved-instance-reporting': ['CE'], 'fault-injection-service': ['FIS'], 'x-ray': ['XRay'], 'deadline-cloud': ['Deadline'],
  'elemental-mediaconnect': ['MediaConnect'], 'elemental-mediaconvert': ['MediaConvert'], 'elemental-medialive': ['MediaLive'],
  'elemental-mediapackage': ['MediaPackageV2','MediaPackage'], 'elemental-mediastore': ['MediaStore'], 'elemental-mediatailor': ['MediaTailor'],
  'interactive-video-service': ['IVS','IVSChat'], 'kinesis-video-streams': ['KinesisVideo'],
  'iot-core': ['IoT','IoTWireless'], 'iot-device-defender': ['IoT'], 'iot-device-management': ['IoT'], 'iot-greengrass-service': ['GreengrassV2','Greengrass'],
  'iot-fleetwise': ['IoTFleetWise'], 'iot-sitewise': ['IoTSiteWise'], 'iot-twinmaker': ['IoTTwinMaker'], 'gamelift-servers': ['GameLift'],
  'quantum-ledger-database': ['QLDB'], 'app-studio': [], 'augmented-ai-a2i': ['SageMaker'], 'codeguru': ['CodeGuruReviewer','CodeGuruProfiler'],
  'healthomics': ['Omics'], 'lex': ['Lex'], 'lookout-for-equipment': ['LookoutEquipment'], 'lookout-for-vision': ['LookoutVision'],
  'lookout-for-metrics': [], 'q': ['QBusiness'], 'nova': ['Bedrock'], 'pinpoint-apis': ['Pinpoint'], 'simple-email-service': ['SES'],
  'end-user-messaging': ['SMSVOICE'], 'supply-chain': ['SCN'], 'chime-sdk': ['Chime'], 'repost-private': [],
};

export const apiAliases = {
  'data-firehose':['firehose'], 'managed-streaming-for-apache-kafka':['kafka','kafkaconnect'],
  'health-dashboard':['health'], 'healthscribe':['transcribe'], 'workdocs-sdk':['workdocs'],
  'snowball-edge':['snowball'], 'marketplace-dark':['marketplace-catalog','marketplace-agreement','meteringmarketplace'],
  'marketplace-light':['marketplace-catalog','marketplace-agreement','meteringmarketplace'],
  'private-5g':['privatenetworks'], 'cloud-control-api':['cloudcontrol'],
  'sagemaker-ai':['sagemaker','sagemaker-runtime'], 'elastic-load-balancing':['elbv2','elb'],
  'virtual-private-cloud':['ec2'], 'vpc':['ec2'], 'identity-and-access-management':['iam'],
  'elastic-container-service':['ecs'], 'elastic-kubernetes-service':['eks'], 'elastic-block-store':['ec2'],
  'application-discovery-service':['discovery'], 'repost-private':['repostspace'], 'security-incident-response':['security-ir'],
};

// Non-managed software, hardware and assistance products need their own
// vocabulary. These are diagram concepts, deliberately not fictional API fields.
const guide = (slug, concepts, source) => ({slug, concepts: concepts.split('|'), source});
export const productGuides = Object.fromEntries([
  guide('private-5g','Private mobile network|Radio units|SIM / device identity|Network site','https://docs.aws.amazon.com/private-networks/latest/userguide/what-is-private-networks.html'),
  guide('cloud-digital-interface','Media application|CDI SDK|EC2 network transport|Uncompressed media stream','https://aws.amazon.com/media-services/resources/cdi/'),
  guide('activate','Startup eligibility|Activate credits|Technical resources|Account benefits','https://aws.amazon.com/activate/'),
  guide('alexa-for-business','Room / shared device|Skill group|User enrollment|Voice interaction','https://aws.amazon.com/alexaforbusiness/'),
  guide('apache-mxnet-on-aws','MXNet program|Training data|Compute / accelerator|Model artifact','https://docs.aws.amazon.com/dlami/latest/devguide/deep-learning-amis-mxnet.html'),
  guide('app-studio','Application pages|Entities / data|Connectors|Automations','https://docs.aws.amazon.com/appstudio/latest/userguide/welcome.html'),
  guide('backint-agent','SAP HANA database|Backint configuration|S3 backup objects|Restore operation','https://docs.aws.amazon.com/sap/latest/sap-hana/aws-backint-agent.html'),
  guide('bottlerocket','OS variant|Container orchestrator|Settings API|Update / rollback','https://bottlerocket.dev/en/os/'),
  guide('cloud-development-kit','App / stack|Construct tree|Synthesized template|CloudFormation deployment','https://docs.aws.amazon.com/cdk/v2/guide/home.html'),
  guide('cloudshell','Console identity|Shell environment|AWS CLI / SDK|Regional storage','https://docs.aws.amazon.com/cloudshell/latest/userguide/welcome.html'),
  guide('codewhisperer','IDE context|Code suggestions|Security scanning|Q Developer identity','https://docs.aws.amazon.com/whitepapers/latest/aws-overview/developer-tools.html'),
  guide('command-line-interface','Profile / credentials|Service / operation|Region / endpoint|JSON input / output','https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html'),
  guide('console-mobile-application','Mobile sign-in|Resource views|Alarms / notifications|CloudShell access','https://docs.aws.amazon.com/consolemobileapp/latest/userguide/what-is-consolemobileapp.html'),
  guide('corretto','OpenJDK distribution|Java application|JVM settings|Platform / version','https://docs.aws.amazon.com/whitepapers/latest/aws-overview/developer-tools.html'),
  guide('data-transfer-terminal','Terminal reservation|Physical transfer site|Customer equipment|AWS destination','https://aws.amazon.com/data-transfer-terminal/'),
  guide('dcv','DCV server|Desktop session|Client authentication|Encrypted pixel stream','https://docs.aws.amazon.com/dcv/latest/adminguide/what-is-dcv.html'),
  guide('deep-learning-amis','EC2 AMI|ML framework|Driver / accelerator|Training environment','https://docs.aws.amazon.com/dlami/latest/devguide/what-is-dlami.html'),
  guide('deep-learning-containers','Container image|Framework / version|Training or inference|ECS / EKS / SageMaker','https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/what-is-dlc.html'),
  guide('deepcomposer','Musical input|Generative model|Composition|Exported music','https://docs.aws.amazon.com/whitepapers/latest/aws-overview/machine-learning.html'),
  guide('deepracer','Reward function|Training simulation|Evaluation track|Vehicle deployment','https://docs.aws.amazon.com/deepracer/latest/developerguide/what-is-deepracer.html'),
  guide('distro-for-opentelemetry','Instrumentation|Receiver|Processor|Exporter / telemetry backend','https://aws-otel.github.io/docs/introduction'),
  guide('eks-anywhere','Management cluster|Workload cluster|Cluster configuration|Infrastructure provider','https://anywhere.eks.amazonaws.com/docs/'),
  guide('eks-distro','Kubernetes distribution|Release manifest|Component images|Self-managed cluster','https://distro.eks.amazonaws.com/'),
  guide('elastic-inference','Attached accelerator|Inference workload|Framework runtime|Accelerator capacity','https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html'),
  guide('elastic-transcoder','Pipeline|Transcoding job|Preset|S3 input / output','https://docs.aws.amazon.com/whitepapers/latest/aws-overview/media-services.html'),
  guide('elemental-appliances-software','On-premises appliance|Encoding|Packaging|Cloud integration','https://docs.aws.amazon.com/whitepapers/latest/aws-overview/media-services.html'),
  guide('elemental-conductor','Managed nodes|Channel configuration|Scheduling|Monitoring','https://docs.aws.amazon.com/elemental-cl3/latest/ug/creating-a-channel.html'),
  guide('elemental-delta','Input content|Packaging filters|Endpoint|Content delivery','https://docs.aws.amazon.com/elemental-delta/'),
  guide('elemental-link','Camera source|Link hardware|Network uplink|MediaLive channel','https://docs.aws.amazon.com/medialive/latest/ug/link.html'),
  guide('elemental-live','Live input|Encoding event|Output groups|Destinations','https://docs.aws.amazon.com/elemental-live/'),
  guide('elemental-server','Input file|Transcoding job|Encoding settings|Output assets','https://docs.aws.amazon.com/elemental-server/'),
  guide('freertos','Microcontroller|RTOS tasks|Connectivity libraries|Device application','https://docs.aws.amazon.com/freertos/latest/userguide/what-is-freertos.html'),
  guide('infrastructure-composer','Visual canvas|Resource cards|Connections|SAM / CloudFormation template','https://docs.aws.amazon.com/whitepapers/latest/aws-overview/developer-tools.html'),
  guide('iot-button','Button event|Device identity|Network connection|Cloud action','https://aws.amazon.com/iotbutton/'),
  guide('iot-expresslink','Host MCU|Connectivity module|AT commands|IoT Core messaging','https://docs.aws.amazon.com/iot-expresslink/latest/programmersguide/elpg.html'),
  guide('iq','Expert request|Proposal|Project access|Payment / review','https://docs.aws.amazon.com/iq/latest/user-guide/what-is-aws-iq.html'),
  guide('local-zones','Parent region|Local Zone subnet|Supported workload|Regional connectivity','https://docs.aws.amazon.com/local-zones/latest/ug/what-is-aws-local-zones.html'),
  guide('lookout-for-metrics','Metric dataset|Anomaly detector|Dimension / measure|Anomaly alert','https://docs.aws.amazon.com/whitepapers/latest/aws-overview/machine-learning.html'),
  guide('managed-services','Managed account|Change request|Monitoring / incidents|Patch / backup operations','https://docs.aws.amazon.com/whitepapers/latest/aws-overview/customer-enablement.html'),
  guide('management-console','Account / role|Region selection|Service console|Resource action','https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/getting-started.html'),
  guide('migration-evaluator','Inventory collection|Utilization analysis|Cost model|Migration business case','https://aws.amazon.com/migration-evaluator/'),
  guide('monitron','Sensor|Gateway|Asset / position|Condition alerts','https://docs.aws.amazon.com/Monitron/latest/user-guide/what-is-monitron.html'),
  guide('neuron','Framework integration|Compiler|Runtime / NeuronCore|Profiling tools','https://awsdocs-neuron.readthedocs-hosted.com/en/latest/'),
  guide('nice-enginframe','HPC portal|Service definition|Job submission|Scheduler integration','https://docs.aws.amazon.com/enginframe/'),
  guide('open-3d-engine','Project|Gems / components|Assets|Runtime / simulation','https://aws.amazon.com/o3de/'),
  guide('parallel-cluster','Head node|Slurm queue|Compute resources|Shared storage','https://docs.aws.amazon.com/parallelcluster/latest/ug/what-is-aws-parallelcluster.html'),
  guide('professional-services','Business objective|Engagement|Implementation workstream|Knowledge transfer','https://aws.amazon.com/professional-services/'),
  guide('pytorch-on-aws','PyTorch program|Training dataset|Compute / accelerator|Model inference','https://aws.amazon.com/pytorch/'),
  guide('red-hat-openshift-service-on-aws','OpenShift cluster|Worker nodes|AWS networking|Operator / workload','https://docs.aws.amazon.com/rosa/latest/userguide/what-is-rosa.html'),
  guide('repost','Question|Topic / tag|Answer|Community knowledge','https://repost.aws/'),
  guide('sagemaker-studio-lab','Project runtime|Notebook|Environment packages|Project files','https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lab.html'),
  guide('service-management-connector','Service management platform|Connector configuration|AWS service integration|Provisioning / operations','https://docs.aws.amazon.com/smc/latest/ag/what-is.html'),
  guide('tensorflow-on-aws','TensorFlow program|Training data|Compute / accelerator|Saved model / serving','https://aws.amazon.com/tensorflow/'),
  guide('thinkbox-deadline','Repository / database|Job / task|Worker pool|Render output','https://docs.thinkboxsoftware.com/products/deadline/10.4/1_User%20Manual/manual/introduction.html'),
  guide('thinkbox-frost','Particle input|Meshing settings|Geometry|DCC integration','https://docs.thinkboxsoftware.com/products/frost/2.3/1_Documentation/'),
  guide('thinkbox-krakatoa','Particle data|Shading / lighting|Particle rendering|Image output','https://docs.thinkboxsoftware.com/products/krakatoa/2.12/1_Documentation/'),
  guide('thinkbox-sequoia','Point cloud|Meshing|Geometry processing|Mesh export','https://docs.thinkboxsoftware.com/products/sequoia/1.1/1_Documentation/'),
  guide('thinkbox-stoke','Particle source|Velocity field|Particle simulation|Cache output','https://docs.thinkboxsoftware.com/products/stoke/2.7/1_Documentation/'),
  guide('thinkbox-xmesh','Animated geometry|Mesh sequence cache|Loader|Scene playback','https://docs.thinkboxsoftware.com/products/xmesh/1.9/1_Documentation/'),
  guide('tools-and-sdks','Language SDK|Credentials / region|API operation|Response / error handling','https://aws.amazon.com/developer/tools/'),
  guide('training-certification','Learning path|Course / lab|Exam preparation|Certification','https://aws.amazon.com/training/'),
  guide('transform','Assessment|Transformation plan|Agent workflow|Validation / migration','https://docs.aws.amazon.com/transform/latest/userguide/transform-environment.html'),
  guide('wavelength','Parent region|Wavelength Zone subnet|Carrier gateway|Edge workload','https://docs.aws.amazon.com/wavelength/latest/developerguide/what-is-wavelength.html'),
].map(p => [p.slug, p]));

export const retiredProducts = ['deepcomposer','elastic-transcoder','elemental-mediastore','iot-analytics','iot-1-click','iot-things-graph','lookout-for-metrics','lookout-for-vision','nice-enginframe','nimble-studio','opsworks','private-5g','quantum-ledger-database','robomaker','simspace-weaver','snowball-edge','snowmobile','sumerian','workdocs','iot-events','iq','panorama'];
export const lifecycleSource = 'https://docs.aws.amazon.com/general/latest/gr/full_shutdown_services.html';

// A primary resource is chosen explicitly where the namespace contains very
// different products. Other resources remain available in the research sheet.
export const primaryTypes = {
  EC2:'Instance', AutoScaling:'AutoScalingGroup', ECR:'Repository', ECS:'Service', EKS:'Cluster', RDS:'DBInstance',
  Lambda:'Function', S3:'Bucket', SQS:'Queue', SNS:'Topic', DynamoDB:'Table', CloudFront:'Distribution', Route53:'HostedZone',
  ElasticLoadBalancingV2:'LoadBalancer', ApiGateway:'RestApi', ApiGatewayV2:'Api', KMS:'Key', IAM:'Role', CertificateManager:'Certificate',
  SecretsManager:'Secret', Cognito:'UserPool', SSO:'PermissionSet', NetworkFirewall:'Firewall', WAFv2:'WebACL',
  ElastiCache:'ReplicationGroup', DocDB:'DBCluster', Neptune:'DBCluster', MemoryDB:'Cluster', FSx:'FileSystem', EFS:'FileSystem',
  StepFunctions:'StateMachine', Events:'EventBus', Kinesis:'Stream', KinesisFirehose:'DeliveryStream',
  Redshift:'Cluster', OpenSearchService:'Domain', MSK:'Cluster', SageMaker:'Endpoint', Bedrock:'Agent',
  CloudWatch:'Alarm', Logs:'LogGroup', CloudTrail:'Trail', SSM:'Document', Organizations:'Organization',
  CodeBuild:'Project', CodePipeline:'Pipeline', CodeDeploy:'DeploymentGroup', CodeCommit:'Repository',
  AppStream:'Fleet', WorkSpaces:'Workspace', AppSync:'GraphQLApi', Amplify:'App', AppRunner:'Service', Batch:'JobDefinition',
  GreengrassV2:'ComponentVersion', IoT:'Thing', IoTSiteWise:'Asset', IoTTwinMaker:'Entity',
};

// Exact icon semantics override service-wide configuration context.
export const exactTypes = {
  'aws-elastic-load-balancing-application-load-balancer':['ElasticLoadBalancingV2::LoadBalancer','ElasticLoadBalancingV2::Listener','ElasticLoadBalancingV2::ListenerRule','ElasticLoadBalancingV2::TargetGroup','ElasticLoadBalancingV2::TrustStore'],
  'aws-elastic-load-balancing-network-load-balancer':['ElasticLoadBalancingV2::LoadBalancer','ElasticLoadBalancingV2::Listener','ElasticLoadBalancingV2::TargetGroup'],
  'aws-elastic-load-balancing-classic-load-balancer':['ElasticLoadBalancing::LoadBalancer'],
  'aws-elastic-load-balancing-gateway-load-balancer':['ElasticLoadBalancingV2::LoadBalancer','ElasticLoadBalancingV2::TargetGroup','EC2::VPCEndpointService'],
  'vpc':['EC2::VPC'], 'private-subnet':['EC2::Subnet'], 'public-subnet':['EC2::Subnet'],
  'security-group':['EC2::SecurityGroup'], 'auto-scaling-group':['AutoScaling::AutoScalingGroup'], 'spot-fleet':['EC2::SpotFleet'],
  'aws-account':['Organizations::Account'], 'ec2-instance-contents':['EC2::Instance'],
  'aws-step-functions-workflow':['StepFunctions::StateMachine'], 'aws-iot-greengrass':['GreengrassV2::ComponentVersion'],
  'aws-iot-greengrass-deployment':['GreengrassV2::Deployment'], 'elastic-beanstalk-container':['ElasticBeanstalk::Environment'],
  'vpc-endpoint':['EC2::VPCEndpoint'], 'aws-vpc-internet-gateway':['EC2::InternetGateway','EC2::VPCGatewayAttachment'],
  'aws-vpc-vpn-gateway':['EC2::VPNGateway','EC2::VPCGatewayAttachment'], 'aws-vpc-nat-gateway':['EC2::NatGateway'],
  'aws-vpc-customer-gateway':['EC2::CustomerGateway'], 'aws-vpc-vpn-connection':['EC2::VPNConnection'],
  'aws-vpc-carrier-gateway':['EC2::CarrierGateway'], 'aws-vpc-elastic-network-interface':['EC2::NetworkInterface'],
  'aws-vpc-network-access-control-list':['EC2::NetworkAcl'], 'aws-vpc-peering-connection':['EC2::VPCPeeringConnection'],
  'aws-vpc-flow-logs':['EC2::FlowLog'], 'aws-vpc-virtual-private-cloud-vpc':['EC2::VPC'],
  'aws-elastic-block-store-volume':['EC2::Volume'], 'aws-ec2-instance':['EC2::Instance'], 'aws-ec2-elastic-ip-address':['EC2::EIP'],
  'aws-s3-bucket':['S3::Bucket'], 'aws-s3-access-points':['S3::AccessPoint'], 'aws-dynamodb-table':['DynamoDB::Table'],
  'aws-sqs-queue':['SQS::Queue'], 'aws-sns-topic':['SNS::Topic'], 'aws-lambda-lambda-function':['Lambda::Function'],
  'aws-aurora':['RDS::DBCluster'], 'aws-client-vpn':['EC2::ClientVpnEndpoint'], 'aws-transit-gateway':['EC2::TransitGateway'],
  'aws-privatelink':['EC2::VPCEndpointService'], 'aws-site-to-site-vpn':['EC2::VPNConnection'], 'aws-verified-access':['EC2::VerifiedAccessInstance'],
  'aws-virtual-private-cloud':['EC2::VPC'], 'aws-cloud-wan':['NetworkManager::CoreNetwork'],
};

// Research/design vocabularies for products which are software, operational
// services, or concepts rather than CloudFormation-managed resources. Sources
// are official product guides; fields are diagram concepts, not claimed APIs.
export const guideFamilies = {
  software: {concepts:['Runtime / installation','Configuration / input','Execution / integration','Output / operations'], source:'https://docs.aws.amazon.com/whitepapers/latest/aws-overview/developer-tools.html'},
  assistance: {concepts:['Account / organization','Request / engagement','Service delivery','Outcome / follow-up'], source:'https://docs.aws.amazon.com/whitepapers/latest/aws-overview/customer-enablement.html'},
  device: {concepts:['Device / site','Identity / provisioning','Connectivity / messages','Cloud integration'], source:'https://docs.aws.amazon.com/whitepapers/latest/aws-overview/internet-of-things-services.html'},
  ai: {concepts:['Input dataset / request','Model / task configuration','Training or inference','Results / evaluation'], source:'https://docs.aws.amazon.com/whitepapers/latest/aws-overview/machine-learning.html'},
  media: {concepts:['Input media','Processing configuration','Output format / destination','Monitoring / delivery'], source:'https://docs.aws.amazon.com/whitepapers/latest/aws-overview/media-services.html'},
  workplace: {concepts:['Organization / directory','User / identity','Application / content','Access / administration'], source:'https://docs.aws.amazon.com/whitepapers/latest/aws-overview/business-applications.html'},
  physical: {concepts:['Location / hardware','Network / capacity','Workload integration','Operations / responsibility'], source:'https://docs.aws.amazon.com/whitepapers/latest/aws-overview/compute-services.html'},
  transfer: {concepts:['Source system','Transfer / migration plan','Target system','Validation / operations'], source:'https://docs.aws.amazon.com/whitepapers/latest/aws-overview/migration-services.html'},
  symbol: {concepts:['Symbol meaning','Owning context','Relationship / direction','Legend / constraints'], source:'https://aws.amazon.com/architecture/icons/'},
};
