//go:build ignore

package main

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type field struct { kind, name string; index int }

func main() {
	root := "."
	if len(os.Args) > 1 { root = os.Args[1] }
	input := filepath.Join(root, "external/engine/abi/fields.csv")
	file, err := os.Open(input); must(err)
	defer file.Close()
	records, err := csv.NewReader(file).ReadAll(); must(err)
	groups := map[string][]field{}
	for row, record := range records[1:] {
		if len(record) != 3 { panic(fmt.Sprintf("ABI schema row %d has %d columns", row+2, len(record))) }
		index, err := strconv.Atoi(record[2]); must(err)
		groups[record[0]] = append(groups[record[0]], field{record[0], record[1], index})
	}
	for kind, fields := range groups {
		sort.Slice(fields, func(i, j int) bool { return fields[i].index < fields[j].index })
		for index, value := range fields { if value.index != index { panic(fmt.Sprintf("ABI %s index gap at %d", kind, index)) } }
		groups[kind] = fields
	}
	writeGo(filepath.Join(root, "internal/usecase/v2/engine_abi_generated.go"), groups)
	writeRust(filepath.Join(root, "external/engine/src/cnf/engine_abi.rs"), groups)
}

func writeGo(path string, groups map[string][]field) {
	var output bytes.Buffer
	output.WriteString("// Code generated by scripts/tool/gen_engine_abi.go; DO NOT EDIT.\n\npackage v2\n")
	for _, kind := range []string{"number", "string", "bool", "resolved_number", "resolved_string"} {
		prefix := map[string]string{"number":"engineNumber", "string":"engineString", "bool":"engineBool", "resolved_number":"engineResolvedNumber", "resolved_string":"engineResolvedString"}[kind]
		output.WriteString("\nconst (\n")
		for _, value := range groups[kind] { fmt.Fprintf(&output, "\t%s%s = %d\n", prefix, camel(value.name), value.index) }
		fmt.Fprintf(&output, "\t%sFieldCount = %d\n", prefix, len(groups[kind]))
		output.WriteString(")\n")
	}
	formatted, err := format.Source(output.Bytes()); must(err)
	must(os.WriteFile(path, formatted, 0o644))
}

func writeRust(path string, groups map[string][]field) {
	var output bytes.Buffer
	output.WriteString("// Code generated by scripts/tool/gen_engine_abi.go; DO NOT EDIT.\n#![allow(dead_code)]\n")
	for _, kind := range []string{"number", "string", "bool", "resolved_number", "resolved_string"} {
		prefix := strings.ToUpper(kind)
		for _, value := range groups[kind] {
			if kind == "bool" {
				fmt.Fprintf(&output, "pub(crate) const %s_%s: u16 = 1 << %d;\n", prefix, strings.ToUpper(value.name), value.index)
			} else {
				fmt.Fprintf(&output, "pub(crate) const %s_%s: usize = %d;\n", prefix, strings.ToUpper(value.name), value.index)
			}
		}
		fmt.Fprintf(&output, "pub(crate) const %s_FIELD_COUNT: usize = %d;\n", prefix, len(groups[kind]))
	}
	must(os.WriteFile(path, output.Bytes(), 0o644))
}

func camel(value string) string {
	var output strings.Builder
	for _, part := range strings.Split(value, "_") { if part != "" { output.WriteString(strings.ToUpper(part[:1])); output.WriteString(part[1:]) } }
	return output.String()
}

func must(err error) { if err != nil { panic(err) } }
