// Code generated by scripts/tool/gen_engine_abi.go; DO NOT EDIT.

package v2

const (
	engineNumberX                 = 0
	engineNumberY                 = 1
	engineNumberWidth             = 2
	engineNumberHeight            = 3
	engineNumberIntrinsicWidth    = 4
	engineNumberIntrinsicHeight   = 5
	engineNumberMinWidth          = 6
	engineNumberMaxWidth          = 7
	engineNumberMinHeight         = 8
	engineNumberMaxHeight         = 9
	engineNumberOffsetX           = 10
	engineNumberOffsetY           = 11
	engineNumberWeight            = 12
	engineNumberGap               = 13
	engineNumberMarginTop         = 14
	engineNumberMarginRight       = 15
	engineNumberMarginBottom      = 16
	engineNumberMarginLeft        = 17
	engineNumberPaddingTop        = 18
	engineNumberPaddingRight      = 19
	engineNumberPaddingBottom     = 20
	engineNumberPaddingLeft       = 21
	engineNumberStrokeWidth       = 22
	engineNumberCornerRadius      = 23
	engineNumberOpacity           = 24
	engineNumberFontSize          = 25
	engineNumberLineHeight        = 26
	engineNumberTextPaddingTop    = 27
	engineNumberTextPaddingRight  = 28
	engineNumberTextPaddingBottom = 29
	engineNumberTextPaddingLeft   = 30
	engineNumberIconWidth         = 31
	engineNumberIconHeight        = 32
	engineNumberIconScale         = 33
	engineNumberIconOffsetX       = 34
	engineNumberIconOffsetY       = 35
	engineNumberPortAnchor        = 36
	engineNumberPortOffset        = 37
	engineNumberPortSize          = 38
	engineNumberSourceAnchor      = 39
	engineNumberTargetAnchor      = 40
	engineNumberObstacleMargin    = 41
	engineNumberLabelPosition     = 42
	engineNumberFieldCount        = 43
)

const (
	engineStringId              = 0
	engineStringTextValue       = 1
	engineStringFontFamily      = 2
	engineStringTextColor       = 3
	engineStringTextRole        = 4
	engineStringIconRef         = 5
	engineStringIconFallbackRef = 6
	engineStringIconColor       = 7
	engineStringFill            = 8
	engineStringStroke          = 9
	engineStringPortLabel       = 10
	engineStringLineSource      = 11
	engineStringLineTarget      = 12
	engineStringLineLabel       = 13
	engineStringFieldCount      = 14
)

const (
	engineBoolVisible     = 0
	engineBoolTextWrap    = 1
	engineBoolTextFit     = 2
	engineBoolTextClip    = 3
	engineBoolPortVisible = 4
	engineBoolLayer       = 5
	engineBoolColumns     = 6
	engineBoolColumnSpan  = 7
	engineBoolRowSpan     = 8
	engineBoolFieldCount  = 9
)

const (
	engineResolvedNumberX             = 0
	engineResolvedNumberY             = 1
	engineResolvedNumberWidth         = 2
	engineResolvedNumberHeight        = 3
	engineResolvedNumberStrokeWidth   = 4
	engineResolvedNumberCornerRadius  = 5
	engineResolvedNumberOpacity       = 6
	engineResolvedNumberFontSize      = 7
	engineResolvedNumberLineHeight    = 8
	engineResolvedNumberLabelPosition = 9
	engineResolvedNumberTextX         = 10
	engineResolvedNumberTextY         = 11
	engineResolvedNumberTextWidth     = 12
	engineResolvedNumberTextHeight    = 13
	engineResolvedNumberIconX         = 14
	engineResolvedNumberIconY         = 15
	engineResolvedNumberIconWidth     = 16
	engineResolvedNumberIconHeight    = 17
	engineResolvedNumberFieldCount    = 18
)

const (
	engineResolvedStringId         = 0
	engineResolvedStringTextValue  = 1
	engineResolvedStringFontFamily = 2
	engineResolvedStringTextColor  = 3
	engineResolvedStringTextRole   = 4
	engineResolvedStringIconRef    = 5
	engineResolvedStringFill       = 6
	engineResolvedStringStroke     = 7
	engineResolvedStringLineLabel  = 8
	engineResolvedStringFieldCount = 9
)
